# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: 团队开源项目
    url: https://github.com/yunzhiclub
  - name: 团队成员
    url: 

# navigation menu
menu:
  - name: 首页
    slug: home
    url: /
  - name: 所有文章
    slug: archives
    url: /archives
  - name: 项目介绍
    url: 
  - name: 最新活动
    slug: gallery
    url: 
  - name: 关于我们
    slug: about
    url: /about

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/mengyunzhi
- slug: rss
  url: /atom.xml
